// Generated by Wrangler on Sun May 12 2024 05:46:33 GMT+0330 (Iran Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	APP_URL: string;
	BOT_TOKEN: string;
}
